# Generated by Django 4.2.7 on 2024-04-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='due_date',
        ),
    ]
