# Generated by Django 4.2.7 on 2024-05-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_todoitem_description_remove_todoitem_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='id',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='task_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
