# Generated by Django 4.2.7 on 2024-05-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_todoitem_id_todoitem_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='task_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
