# Generated by Django 4.2.7 on 2024-05-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_todoitem_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='stat',
            field=models.BooleanField(default=False),
        ),
    ]
