# Generated by Django 4.2.7 on 2024-05-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_todoitem_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.TextField(max_length=500),
        ),
    ]
